name: "ðŸ’¨ Duty Cal smoke test"
on: [workflow_dispatch]
#on: [push]
jobs:
  cypress-run:
    name:ðŸ’¨ DC Smoke on Chrome
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          repository: TransformCore/trade-tariff-testing
          ref: refs/heads/main
      - uses: cypress-io/github-action@v2
        with:
          quiet: false
          browser: chrome
          headless: true
          spec: "cypress/integration/DutyCalculator/dcShared/dcSmokeTestCI.spec.js"
